#version: '4.38.0'
services:
  postgresql:
    image: postgres:14-alpine3.20
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=login
      - POSTGRES_PASSWORD=qwerty123
